/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bandage: typeof import('./components/Bandage.vue')['default']
    IconCPU: typeof import('./components/icon/IconCPU.vue')['default']
    IconDisk: typeof import('./components/icon/IconDisk.vue')['default']
    IconDownload: typeof import('./components/icon/IconDownload.vue')['default']
    IconLayoutFlex: typeof import('./components/icon/IconLayoutFlex.vue')['default']
    IconLayoutGrid: typeof import('./components/icon/IconLayoutGrid.vue')['default']
    IconLayoutList: typeof import('./components/icon/IconLayoutList.vue')['default']
    IconMemory: typeof import('./components/icon/IconMemory.vue')['default']
    IconSettings: typeof import('./components/icon/IconSettings.vue')['default']
    IconUpload: typeof import('./components/icon/IconUpload.vue')['default']
    Progress: typeof import('./components/Progress.vue')['default']
    ServerCard: typeof import('./components/ServerCard.vue')['default']
    ServerItem: typeof import('./components/ServerItem.vue')['default']
    SettingItem: typeof import('./components/SettingItem.vue')['default']
    StatusChart: typeof import('./components/StatusChart.vue')['default']
    StatusIndicator: typeof import('./components/StatusIndicator.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
  }
}
